---
title: "NEH Grants Data Analysis"
author: "Brian A. Danielak"
format: 
  html:
    toc: true
editor: visual
---

# Loading and Cleaning the Data

## Loading Necessary Libraries

```{r}
#| echo: false
#| message: false
library(tidyverse)
library(vroom)
library(xml2)
```

## Loading Grant Data from Downloaded XML

```{r}
load_grants_from_raw_xml <- function(path_to_xml) {
  
  # First, we check if the rectangularized file already exists.
  if (file.exists("data-cleaned/grants-data-cleaned.tsv")) {
    
    # If it exists, we load it and return it
    grants_cleaned <- vroom::vroom("data-cleaned/grants-data-cleaned.tsv")
    return(grants_cleaned)
  
  # Otherwise, we do the expensive thing
  } else {
      grants_raw <- xml2::read_xml(path_to_xml) |> 
        xml2::as_list()
      
      grants_tibble <- grants_raw$Grants |> 
        lapply(unlist) |> 
        dplyr::bind_rows()
  
      # Write the file out so we can load it next time
      grants_tibble |> 
        dplyr::transmute_all(unlist) |> 
        vroom::vroom_write("data-cleaned/grants-data-cleaned.tsv")
      
      # Load the file (vroom will help infer column types automatically on load)
      grants_cleaned <- vroom::vroom("data-cleaned/grants-data-cleaned.tsv") 
      return(grants_cleaned)
  }
}

# I downloaded and unzipped the 2000s grant data
grants_2000s <- load_grants_from_raw_xml("data-raw/NEH_Grants2000s_Flat/NEH_Grants2000s_Flat.xml")
```
